site_name: didimpute
site_url: "https://dwh3.github.io/did_imputation/"
repo_url: "https://github.com/dwh3/did_imputation"
use_directory_urls: false

theme:
  name: material

nav:
  - Overview: index.md
  - External Review Update: EXTERNAL_REVIEW_UPDATE.md
  - Parity Validation: PARITY.md
  - Intelligence:
      - Intelligence Report: INTELLIGENCE_REPORT.md
      - Intelligence Summary: INTELLIGENCE_SUMMARY.md
      - Docs Deploy Status: DOCS_DEPLOY_STATUS.md
      - Release Status: RELEASE_STATUS.md
      - Specification: SPEC.md
